### PR TITLE
add breeze theme

### PR DESCRIPTION
**Pull request by jklmnn**
Added a theme based on KDEs Breeze colors.

### CODE REVIEW

**Comment by okraits** [comment]
Thank you for your contribution!

Could you please use different colors for `client.focused` and `client.focused_inactive`?

focus

In the screenshot above you can't tell wether the window at the top left or the window at the top right is focused because they have the same colors.

And I would use a different text color for the focused workspace button (2: code) - maybe the same text colors as for the active and inactive workspace buttons?

**Comment by jklmnn** [comment]
Thanks for the feedback. I didn't notice this as I have tuned all borders off.
For the text I have used the actual colors of the Breeze dark theme. But you're right it doesn't have the best contrast.
I'll take a look and fix that.

Just a slight off topic question. What is you status line? I really like it.

**Comment by okraits** [comment]
I use [i3blocks](https://github.com/vivien/i3blocks).
The icons in the statusline come from [FontAwesome](http://fontawesome.io/).

**Comment by jklmnn** [comment]
I have changed the colors, so you can take a look.

**Comment by okraits** [comment]
The titlebars are good now. 

Unfortunately I didn't try the theme with titlebars disabled when I wrote my first reply. So I just noticed that there's also an issue to determine the focused window when titlebars are disabled (`border pixel 3` for example) because all child borders are white. Is that intentional?

How do you determine the focused window with all borders turned off? With the help of window fading?

Sorry for being so nitpicky.

**Comment by jklmnn** [comment]
> Sorry for being so nitpicky.
No problem ;)

Actually I run a setup with i3 on KDE Plasma so I don't have the i3bar on my main screen and can see the focused window in the Plasma bar. On all other screens I usually only work in tabbed full screen so that isn't a problem for me.

I'll take a look on a system with a default i3 config and try to get the colours complete and matching.

**Comment by jklmnn** [comment]
I have fixed the window borders. They*re equal to the title bar now.

**Comment by okraits** [comment]
Merged in https://github.com/okraits/j4-make-config/commit/6adf3ff96123501aadc1e8588841173c504b584f.

Thank you for your contribution!

**Pull request closed without merging**
